### ISSUE TITLE
Change Title on the Post page to Book Title

### ISSUE THREAD

**Issue by mgrobi03** [CSE-550/Bookish#42]

**Comment by GrizzlyEnglish** [comment]
@mgrobi03 Can you add more information? The title of the post is meant to be the book title.

**Comment by mgrobi03** [comment]
![image](https://user-images.githubusercontent.com/79548398/111892035-f6fcdd80-89cd-11eb-88c6-38d3616a16f8.png)
Should this say maybe "Book Title" or just "Title" instead of "Post Title"? It would be an easy way to bring this project closer to the theme of books.
