### ISSUE TITLE
Front page: when the user did not voted both icons are actives.

### ISSUE THREAD

**Issue by Lucia-Cristina** [CSE-550/Bookish#90]
corrected

**Comment by GrizzlyEnglish** [comment]
This is intended

**Comment by Lucia-Cristina** [comment]
Ryan it does not make sense. On Reddit it works with the 2 icons not active when user has not voted yet.

**Comment by Lucia-Cristina** [comment]
In all social medias works on this way.
![image](https://user-images.githubusercontent.com/63417263/114308772-e9a9af00-9ab2-11eb-943f-86002a1e2e9a.png)
This is on YouTube


![image](https://user-images.githubusercontent.com/63417263/114308836-2bd2f080-9ab3-11eb-8147-bad1f3569ba5.png)
on Reddit

**Comment by GrizzlyEnglish** [comment]
We flipped due to using an emoji rather than an icon, but that is fine.
